FROM ubuntu:latest
MAINTAINER Bala "balab@microsoft.com"
RUN apt-get update -y
RUN apt-get install -y python-pip python-dev build-essential
EXPOSE 80 443
COPY . /app
WORKDIR /app
RUN pip install -r requirements.txt
ENTRYPOINT ["python"]
CMD ["xgbweb.py"]

